name: Super Linter CI

on:
  push:
    branches: [ "main", develop ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Super-Linter
      uses: super-linter/super-linter@v8.0.0
