name: Discord notification

on:
  - push

jobs:
  discord-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: tenzin1308/discord-notification@v1.0.0
        with:
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}